### PR TITLE
Move from autocorr to crosscorr

### PR DESCRIPTION
**Pull request by oyssolbo**
Major changes to analyze-data, as the class Hydrophone has been dropped

I'm a bit uncertain about the correctness of some arrays:
-at line 182 and 189 I make an array to hold some specific values that are later changed in a function. Will the original values be changed?

Note: some of the code from my debugging session during the work-week has been included. This must be dealt with in another pr/issue

### CODE REVIEW

**Comment by oyssolbo** [comment]
Just starting thinking how we would detect which hydrophone measures the signal first. Using the crosscorrelation, we would only get the TDOA in absolute value.

**Comment by oyssolbo** [comment]
And I realize that the switch from autocorr to crosscorr has large effects on other parts of the code. Do NOT approve the PR. Repeat: Do NOT approve the pr until this is sorted out

**Comment by oyssolbo** [comment]
To get the crosscorr right, we have to detect the polarity of the index.

If H1 and H2 are signals, and x denotes the cross-correlation between them:

Assuming that H1 arrives before H2 with n timesteps

=> 

arg max( H1 x H2 ) = n

arg max( H2 x H1 ) = - n


Please notify if I've swapped the sign here ^^


To get the correct index n, we must therefore do a linear shift of the estimated index-number n_hat

**Comment by oyssolbo** [comment]
Currently (after way too many hours of refactoring), I would consider the code reasonable. Would therefore encourage a pr (if the code looks good otherwise)

**Comment by oyssolbo** [comment]
Think I eliminated a possible bug, where the matrices A and B were set to the same value and thus resulted in the same position-estimate every time. See changes to calculate_tdoa_matrices in trilateration.cpp

**Review by chrstrom — APPROVED** [review]
lgtm 👍

**Pull request merged**
